export const SOLO_PROJECTS: MainProps[] = [
    { id: 1, title: 'Web Portafolio', description: 'Proyecto <a href="www.efraincaicedo.com" target="_blank" className="text-primaryOrange">www.efraincaicedo.com</a>. Página web desarrollada en colaboración estrecha con el cliente quien fue el creador del diseño, utilizando Next.js y Tailwind CSS. El resultado de este proyecto es una web con un excelente performance, buenas practicas, accesiobilidad y SEO.', englishDescription: 'Project <a href="www.efraincaicedo.com" target="_blank" className="text-primaryOrange">www.efraincaicedo.com</a>. Website developed in close collaboration with the client, who was the creator of the design, using Next.js and Tailwind CSS. The outcome of this project is a website with excellent performance, good practices, accessibility, and SEO.', bgButtonColor: 'bg-primaryGreen', img: '/images/projects/efra-portfolio.png', titleButton: 'Web - Portfolio', url: 'https://efraincaicedo.com/', mobileDescription: 'Proyecto <a href="www.efraincaicedo.com" target="_blank" className="text-primaryOrange">www.efraincaicedo.com</a>. Página web desarrollada en colaboración estrecha con el cliente quien fue el creador del diseño, utilizando Next.js y Tailwind CSS.', mobileEnglishDescription: 'Project <a href="www.efraincaicedo.com" target="_blank" className="text-primaryOrange">www.efraincaicedo.com</a>. Website developed in close collaboration with the client, who was the creator of the design, using Next.js and Tailwind CSS.' },
    {
        id: 2, title: 'Madrugón Mayorista', description: 'Proyecto <span className="text-primaryOrange">Madrugón Mayorista</span>. Este proyecto de tienda en línea se desarrolla con Next.js, Tailwind CSS y Supabase, combinando renderizado eficiente, diseño responsivo y gestión de datos en tiempo real.En construcción, busca ofrecer una experiencia de usuario óptima y un proceso de compra ágil, con una plataforma escalable y fácil de mantener.', englishDescription: 'Project <span className="text-primaryOrange">Madrugón Mayorista</span>.This online store project is being developed using Next.js, Tailwind CSS, and Supabase, combining efficient rendering, responsive design, and real-time data management. Currently under construction, it aims to deliver an optimal user experience and a streamlined purchasing process, with a scalable and maintainable platform.', bgButtonColor: 'bg-primaryGreen', img: '/images/projects/madrugon-store.png', titleButton: 'Online', url: '#', mobileDescription: 'Proyecto <span className="text-primaryOrange">Madrugón Mayorista</span>. Página web desarrollada en colaboración estrecha con el cliente quien fue el creador del diseño, utilizando Next.js y Tailwind CSS.', mobileEnglishDescription: 'Project <span className="text-primaryOrange">Madrugón Mayorista</span>. Website developed in close collaboration with the client, who was the creator of the design, using Next.js and Tailwind CSS.'
    }
]
export const PROJECTS_AS_EMPLOYEE: MainProps[] = [
    {
        id: 1, title: 'Aviva Web', description: 'Proyecto <a href="www.aviva.pe" target="_blank" className="text-primaryOrange">www.aviva.pe</a>. Este proyecto combina Next.js, SASS y Django para crear un sitio web dinámico, con un diseño elegante y una gestión de contenido eficiente.Utiliza Next.js para una experiencia de usuario fluida, SASS para estilos avanzados y Django como CMS robusto para el backend.', englishDescription: 'Project <a href="www.aviva.pe" target="_blank" className="text-primaryOrange">www.aviva.pe</a>. This project merges Next.js, SASS, and Django to craft a dynamic website, featuring sleek design and efficient content management. It employs Next.js for a seamless user experience, SASS for advanced styling, and Django as a robust CMS for the backend.', bgButtonColor: 'bg-primaryGreen', img: '/images/projects/aviva.png', titleButton: 'Web - Portfolio', url: 'https://aviva.pe/', mobileDescription: 'Proyecto <a href="www.aviva.pe" target="_blank" className="text-primaryOrange">www.aviva.pe</a>. Página web desarrollada en colaboración estrecha con el cliente quien fue el creador del diseño, utilizando Next.js y Tailwind CSS.', mobileEnglishDescription: 'Project <a href="www.aviva.pe" target="_blank" className="text-primaryOrange">www.aviva.pe</a>. Website developed in close collaboration with the client, who was the creator of the design, using Next.js and Tailwind CSS.'
    },
    { id: 2, title: 'Up', description: 'Proyecto <a href="https://up.alimdreams.com" target="_blank" className="text-primaryOrange">Up e-learning</a>. Página web desarrollada en colaboración estrecha con el cliente quien fue el creador del diseño, utilizando Next.js y Tailwind CSS. El resultado de este proyecto es una web con un excelente performance, buenas practicas, accesiobilidad y SEO.', englishDescription: 'Project <span className="text-primaryOrange">Up e-learning</span>. Website developed in close collaboration with the client, who was the creator of the design, using Next.js and Tailwind CSS. The outcome of this project is a website with excellent performance, good practices, accessibility, and SEO.', bgButtonColor: 'bg-primaryGreen', img: '/images/projects/up.png', titleButton: 'Online', url: 'https://up.alimdreams.com', mobileDescription: 'Proyecto <span className="text-primaryOrange">Up e-learning</span>. Página web desarrollada en colaboración estrecha con el cliente quien fue el creador del diseño, utilizando Next.js y Tailwind CSS.', mobileEnglishDescription: 'Project <span className="text-primaryOrange">Up e-learning</span>. Website developed in close collaboration with the client, who was the creator of the design, using Next.js and Tailwind CSS.' }
]